services:
  db:
    image: postgres
    restart: always
    environment: &psqlenv # these will be reused below [compose fragment concept]
      POSTGRES_PASSWORD: tothemoon
      POSTGRES_USER: apollo
      POSTGRES_DB: apollo11
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
  mongo:
    image: mongodb/mongodb-community-server
    restart: always
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - 27017:27017
    networks:
      - backend
volumes:
  db-data:
    name: "postgres"
  mongo-data:
    name: "mongodb"
networks:
  backend:
