site_name: Apollo 11
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.expand
    - toc.follow
    - navigation.top


nav:
  - Home: index.md
  - readme: accio/readme.md
  - Blog:
      - blog/index.md
plugins:
  - blog

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format