apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: kub
spec:
  selector:
    matchLabels:
      app: kub
  replicas: 3
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
      - name: kub
        image: fast-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx-deployment
#   labels:
#     app: kub
# spec:
#   type: LoadBalancer
#   selector:
#     app: kub
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: LoadBalancer
#   # Uncomment the below line to create a Headless Service
#   # clusterIP: None
#   selector:
#     app: kub
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 80