apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - operator: Exists
      containers:
        - name: traefik
          image: traefik:v3.1
          args:
            - --providers.kubernetesingress
            - --entrypoints.web.address=:8000
            - --entrypoints.websecure.address=:8443
            - --entrypoints.websecure.http.tls=true
            - --log.level=INFO
            - --accesslog=true
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
