apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: apollo-airlines-ui
  labels:
    app: curl-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.5.0
      command: ["sleep", "3600"]
