apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: paymentdb
  name: paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: paymentdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: paymentdb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: apollo11
            - name: MYSQL_PASSWORD
              value: tothemoon
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: apollo
          image: mysql
          name: paymentdb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: payment-db-data
      restartPolicy: Always
      volumes:
        - name: payment-db-data
          persistentVolumeClaim:
            claimName: payment-db-data
