apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo11-observability
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apollo-airlines
    app.kubernetes.io/component: observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apollo-airlines
  source:
    repoURL: https://github.com/darshan-raul/Apollo11.git
    targetRevision: HEAD
    path: stages/stage6/argocd/platform/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: apollo-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
