apiVersion: v1
kind: Secret
type: Opaque
immutable: false
metadata:
  name: bookinginit
  namespace: apollo11
# followed this guide to create a pgpass secret as the usual PGPASSWD way was not working
# https://medium.com/@phil.poon/automated-postgresql12-backups-in-k8s-using-pg-dump-and-pgpass-c7005bddc12d
# hostname:port:database:username:password encoded to base64
data:
  .pgpass: Ym9va2luZ2RiLTAuYm9va2luZ2RiLmFwb2xsbzExLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzI6YXBvbGxvMTE6YXBvbGxvOnRvdGhlbW9vbgo=