apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hazelcast
    env: prod
  name: hazelcast
spec:
  containers:
  - image: nginx
    name: hazelcast

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hazelcast
  name: mytest
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: hazelcast
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - image: busybox
        name: busybox
        ports:
        - containerPort: 5701
