apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: booking
  namespace: apollo11
data:
  PSQL_HOST: "bookingdb"
  PSQL_DB: "apollo11"
  MOVIE_HOST: "movie"
  MOVIE_PORT: "8000"
  THEATRE_HOST: "theatre"
  THEATRE_PORT: "7000"
