apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: moviemongo
  name: moviemongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: moviemongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: moviemongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
          image: mongo
          name: moviemongo
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: movie-mongo-data
      restartPolicy: Always
      volumes:
        - name: movie-mongo-data
          persistentVolumeClaim:
            claimName: movie-mongo-data
