apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: movie-mongo-data
  name: movie-mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
